.Dd January 10, 2019
.Dt JAIL_EXPORTER 8
.Os
.Sh NAME
.Nm jail_exporter
.Nd Prometheus exporter for jail metrics
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl -help
.Op Fl -version
.Nm
.Op Fl Fl web.listen-address Ns = Ns Ar addr:port
.Op Fl Fl web.telemetry-path Ns = Ns Ar path
.Sh DESCRIPTION
.Nm jail_exporter
is a Prometheus exporter for jail metrics.
The options are as follows:
.Bl -tag -width indent
.It Fl h , Fl Fl help
Prints help information
.It Fl V , Fl Fl version
Prints version information
.It Fl Fl web.listen-address= Ns Ar addr:port
Specify an
.Ar addr:port
on which to expose the metrics and web interface.
Defaults to
.Dq Cm 127.0.0.1:9452 .
If specifying an IPv6
.Ar addr:port
the address portion should be enclosed within square brackets, for example:
.Dq Cm [::1]:9452 .
.It Fl Fl web.telemetry-path= Ns Ar path
Specify a
.Ar path
under which to expose the metrics.
Defaults to
.Dq Cm /metrics .
.El
.Sh USAGE
.Nm
must be run as
.Dq root
in order to access the required
.Xr rctl 8
APIs.
Although
.Fx
ships with RACCT/RCTL support in the kernel, it is disabled by default.
It can be enabled by setting
.Va kern.racct.enabled Ns = Ns Qq Ar 1
in
.Pa /boot/loader.conf .
After setting this, a reboot will be required to enable RACCT/RCTL.
.Sh METRICS
The metrics that are exported are those listed in the RESOURCES section of
.Xr rctl 8 ,
and two additional metrics:
.Bl -tag -width num
.It Va id
The ID of the named jail
.It Va num
The current number of jails running.
Does not possess a
.Dq name
label as it is just a simple gauge representing the number of running jails.
.El
.Pp
All metrics are prefixed with the string
.Dq jail_
and in all cases except for the
.Dq num
metric (as mentioned above) possess a
.Dq name
label containing the name of the jail.
An example of a metric output by the exporter would be:
.Bd -literal -offset indent
# HELP jail_cputime_seconds_total CPU time, in seconds
# TYPE jail_cputime_seconds_total counter
jail_cputime_seconds_total{name="test"} 300
.Ed
.Sh "ENVIRONMENT VARIABLES"
.Nm
can also take its configuration from environment variables.
In the event that both command line options and environment variables are
specified, the command line options will win.
.Bl -tag -width JAIL_EXPORTER_WEB_LISTEN_ADDRESS
.It Ev JAIL_EXPORTER_WEB_LISTEN_ADDRESS
is equivalent to setting the
.Fl Fl web.listen-address
option.
.It Ev JAIL_EXPORTER_WEB_TELEMETRY_PATH
is equivalent to setting the
.Fl Fl web.telemetry-path
option.
.El
.Sh FILES
.Bl -tag -width /usr/local/etc/rc.d/jail_exporter -compact
.It Pa /usr/local/etc/rc.d/jail_exporter
the rc.d script
.It Pa /usr/local/sbin/jail_exporter
the exporter daemon
.El
.Sh SEE ALSO
.Xr rctl 4 ,
.Xr loader.conf 5 ,
.Xr jail 8 ,
.Xr rctl 8
.Sh HISTORY
.Nm
was started during the summer of 2018 on
.Fx 11.1 .
.Sh AUTHORS
.Nm
was developed by
.An David O'Rourke
with contributions from
.An Fabian Freyer .
.Sh BUGS
Please report bugs, issues, and feature requests to
.Lk https://github.com/phyber/jail_exporter/issues
