.Dd January 10, 2019
.Dt JAIL_EXPORTER 8
.Os
.Sh NAME
.Nm jail_exporter
.Nd Prometheus exporter for jail metrics.
.Sh SYNOPSIS
.Nm
.Op Fl hV
.Op Fl -help
.Op Fl -version
.Nm
.Op Fl Fl web.listen-address Ns = Ns Ar addr:port
.Op Fl Fl web.telemetry-path Ns = Ns Ar path
.Sh DESCRIPTION
.Nm jail_exporter
is a Prometheus exporter for jail metrics. The metrics that are
exported are listed in the RESOURCES section of rctl(8). The options are as
follows:

.Bl -tag -width indent
.It Fl h , Fl Fl help
Prints help information
.It Fl V , Fl Fl version
Prints version information
.It Fl Fl web.listen-address= Ns Ar addr:port
Specify an
.Ar addr:port
on which to expose the metrics and web interface.
Defaults to
.Dq Cm 127.0.0.1:9452
.Ns .
If specifying an IPv6
.Ar addr:port
the address portion should be enclosed within square brackets. Eg:
.Dq Cm [::1]:9452
.Ns .
.It Fl Fl web.telemetry-path= Ns Ar path
Specify a
.Ar path
under which to expose the metrics.
Defaults to
.Dq Cm /metrics Ns .
.El
