---
task:
    name: 'Cargo Test'
    freebsd_instance:
        matrix:
            - image: 'freebsd-14-1-release-amd64-ufs'
            - image: 'freebsd-13-4-release-amd64'
    env:
        CARGO_HOME: '${HOME}/.cargo'
        CIRRUS_SHELL: '/bin/sh'
    pkg_prepare_script: |
        pkg_repos_dir="/usr/local/etc/pkg/repos"
        mkdir -p "${pkg_repos_dir}"
        cat > "${pkg_repos_dir}/FreeBSD.conf" <<'EOF'
        FreeBSD: {
            url: "pkg+http://pkg.freebsd.org/${ABI}/latest"
        }
        EOF
    install_script: |
        pkg install --yes \
            curl \
            libnghttp2 \
            rust
    before_cache_script: 'rm -rf ${CARGO_HOME}/registry/index'
    cargo_cache:
        fingerprint_script: 'cat Cargo.lock'
        folder: '${CARGO_HOME}/registry'
    test_script: 'cargo test'
    build_script: 'cargo build'
    lint_script: 'cargo clippy --all-targets'
