---
name: 'Continuous Integration'

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - freebsd_version: "13.5"
          - freebsd_version: "14.4"
          - freebsd_version: "15.1"
    name: FreeBSD ${{ matrix.freebsd_version }}
    steps:
      - uses: actions/checkout@v6
      - name: Start VM
        uses: vmactions/freebsd-vm@v1
        with:
          release: ${{ matrix.freebsd_version }}
          usesh: true
      - name: Install dependencies
        shell: freebsd {0}
        run: pkg install -y rust
      - name: Build
        shell: freebsd {0}
        run: cargo build
      - name: Test
        shell: freebsd {0}
        run: cargo test
      - name: Clippy
        shell: freebsd {0}
        run: cargo clippy --all-targets
      - name: mandoc
        shell: freebsd {0}
        run: make manlint
